algo = input('Digite algo: ')
print(f'{algo} é Alfanumérico? {algo.isalnum()}')
print(f'{algo} é alfabético? {algo.isalpha()}')
print(f'{algo} é um dígito? {algo.isdigit()}')
print(f'{algo} está em minúsculo?  {algo.islower()}')
print(f'{algo} é decimal? {algo.isdecimal()}')
print(f'{algo} é numérico? {algo.isnumeric()}')
print(f'{algo} pode ser impresso? {algo.isprintable()}')
print(f'{algo} é um espaço? {algo.isspace()}')
print(f'{algo} é decimal? {algo.isdecimal()}')
print(f'{algo} está em maiúsculo? {algo.isupper()}')
